#ifndef INFOSTORY_HPP_
#define INFOSTORY_HPP_

const char* station_keeper_enemy_info="  GUARDIANO DELLA BASE\n  TIPO DI DANNO: DA FUOCO\n  RESISTENZA: ARMI DA TAGLIO\n  VULNERABILITA': ARMI SPECIALI\n\n  Guardie non specializzate, dotate di poche armi rudimentali e poche protezioni.\n  Assomigliano a delle guardie di un carcere, e il loro compito principale è quello di controllare i prigionieri e allertare i piani alti quando qualcosa non va.\n  Non si sa se sono lì per loro volontà, oppure se sono stati costretti.\n";
const char* toxic_nurse_enemy_info="  INFERMIERA TOSSICA\n  TIPO DI DANNO: VELENO\n  RESISTENZA: NESSUNA\n  VULNERABILITA': ARMI DA MISCHIA\n\n  Dall'aspetto inconfondibile, sono il frutto della peggior ironia della natura.\n  La loro bellezza è svanita, soggiogata da masse purulente contenenti veleno letale.\n";
const char* energumen_mutated_enemy_info="  ENERGUMENO MUTATO\n  TIPO DI DANNO: ARMA CHIMICA\n  RESISTENZA: ARMI DA MISCHIA\n  VULNERABILITA': ARMI DA TAGLIO\n\n  Gigantesca massa di cicatrici ed esperimenti da laboratorio.\n  Carica il bersaglio, correre non serve.\n";
const char* scaled_experiment_enemy_info="  ESPERIMENTO SQUAMATO\n  TIPO DI DANNO: VELENO\n  RESISTENZA: ARMI DA TAGLIO\n  VULNERABILITA': ARMI DA FUOCO PESANTI\n\n  Rinchiuso in ambiente umido ha sviluppato doti fisiche non comuni a tutti gli altri esseri umani.\n  E' uno dei primi esperimenti del dottor Miller, volti a scoprire di più sulla rigenerazione delle cellule umane.\n  Impossibile confonderlo con un animale, le squame che lo pervadono lungo tutto il corpo riflettono la luce e ti stordiscono.\n";
const char* river_guardian_enemy_info="  GUARDIANO DEL FIUME\n  TIPO DI DANNO: DA FUOCO\n  RESISTENZA: ARMI DA FUOCO LEGGERE\n  VULNERABILITA': ARMI DA TAGLIO\n\n  Forse una volta faceva parte del team di manutenzione idrica. Ora non è altro che una creatura priva di senno, ma l'abilità con le armi da fuoco è rimasta.\n";
const char* sewer_walker_enemy_info="  CAMMINATORE DELLE FOGNE\n  TIPO DI DANNO: DA TAGLIO\n  RESISTENZA: ARMI DA MISCHIA\n  VULNERABILITA': ARMI ESPLOSIVE\n\n  Essere gigantesco che popola il fiume sotterraneo che scorre sotto la prigione. Se riesce a trovare un'arma da taglio può essere molto difficile da neutralizzare.\n";
const char* underground_prisoner_enemy_info="  PRIGIONIERO DEI SOTTERRANEI\n  TIPO DI DANNO: AGENTI CHIMICI\n  RESISTENZA: NESSUNA\n  VULNERABILITA': ARMI DA FUOCO LEGGERE\n\n  Prigioniero scappato dalla prigione pervaso da un incontrollabile violenza. La pazzia lo divora e lo sostiene allo stesso tempo.\n";
const char* mad_doctor_enemy_info="  DOTTORE PAZZO\n  TIPO DI DANNO: ARMA CHIMICA\n  RESISTENZA: ARMI SPECIALI\n  VULNERABILITA': ARMI DA TAGLIO\n\n  Probabilmente facente parte di qualche team di ricerca militare. E' stato dilaniato dalla sua stessa sete di sapere che lo ha portato a fare pericolosi esperimenti.\n";
const char* improved_soldier_enemy_info="  SOLDATO MODIFICATO\n  TIPO DI DANNO: DA TAGLIO\n  RESISTENZA: ARMI DA FUOCO PESANTI\n  VULNERABILITA': ARMI ESPLOSIVE\n\n  Che fosse questo l'obiettivo principale? Creare dei super-soldati è sempre stato il sogno di ogni nazione militarizzata.\n  L'aspetto è sufficiente per comprendere la potenza fisica del DNA umano modificato.\n";
const char* cyborg_fighter_enemy_info="  COMBATTENTE CYBORG\n  TIPO DI DANNO: DA FUOCO\n  RESISTENZA: ARMI ESPLOSIVE\n  VULNERABILITA': ARMI SPECIALI\n\n  Incredibilmente pericoloso, questa combattente è costituito da una parte organica e da una parte elettronica.\n  Gli innesti artificiali lo rendono insensibile al dolore e immensamente preciso.\n";


#endif
