#ifndef WEAPONINFO_HPP_
#define WEAPONINFO_HPP_

const char* fasce_da_combattimento_weapon_info="TIRAPUGNI\nTIPO DI DANNO: MISCHIA\nPESO: 2\n\nEFFICACE CONTRO\t<Infermiera Tossica>\nRESISTENTE A\t<Energumeno Mutato>\n\nArma tipica del rissaiolo, questi gioiellini si contraddistinguono per un'incredibile capacità dissuasiva.\n";
const char* manganello_weapon_info="MANGANELLO\nTIPO DI DANNO: DA MISCHIA\nPESO: 3\n\nEFFICACE CONTRO\t<Infermiera Tossica>\nRESISTENTE A\t<Energumeno Mutato>\n\nLa macchia di sangue sul lato fa ben immaginare come sia stato usato. Forse una rivolta interna?";
const char* mazza_weapon_info="MAZZA CHIODATA\nTIPO DI DANNO: DA MISCHIA\nPESO: 4\n\nEFFICACE CONTRO\t<Infermiera Tossica>\nRESISTENTE A\t<Energumeno Mutato>\n\nDi stampo medievale, ma ancora efficace contro i più resistenti. La stanza degli interrogatori potrebbe essere il suo luogo di provenienza.\n";
const char* scure_weapon_info="SCURE ANTINCENDIO\nTIPO DI DANNO: DA TAGLIO\nPESO: 3\n\nEFFICACE CONTRO\t<Energumeno Mutato>\nRESISTENTE A\t<Guardiano della Base>\n\nTipico arnese frangi-vetro presente in ogni stabilimento come misura di sicurezza. Nessuno vieta di usarla per altri scopi.\n";
const char* coltello_weapon_info="BISTURI\nTIPO DI DANNO: DA TAGLIO\nPESO: 3\n\nEFFICACE CONTRO\t<Energumeno Mutato>\nRESISTENTE A\t<Guardiano della Base>\n\nCompagno fedele di ogni chirurgo, è risaputa l'efficacia della sua lama nell'incidere carne e organi. Forse una sala operatoria...";
const char* pistola_weapon_info="Colt M1911\nTIPO DI DANNO: DA FUOCO LEGGERO\nPESO: 4\nMUNIZIONI: 16\n\nEFFICACE CONTRO\t<Prigioniero dei sotteranei>\nRESISTENTE A\t<Guardiano del fiume>\n\nPistola di ordinanza degli Stati Uniti fin dal 1911. Il motivo per cui sia in un posto come questo non è chiaro ma può rivelarsi molto utile.\n";
const char* sparachiodi_weapon_info="SPARACHIODI\nTIPO DI DANNO: SPECIALE\nPESO: 5\nMUNIZIONI: 8\n\nEFFICACE CONTRO\t<Guardiano della Base>\nRESISTENTE A\t<Dottore pazzo>\n\nPrecisione moderata e chiodi ferroviari arrugginiti, la ricetta per una buona Sparachiodi\n";
const char* laser_chirurgico_weapon_info="LASER CHIRURGICO\nTIPO DI DANNO: SPECIALE\nPESO: 2\n\nEFFICACE CONTRO\t<Guardiano della Base>\nRESISTENTE A\t<Dottore pazzo>\n\nUtilizzato in sala operatoria, convoglia la luce emessa in un unico punto, in modo da creare un raggio ad alte frequenze che permette di penetrare la carne\n";
const char* uzi_weapon_info="Thompson\nTIPO DI DANNO: DA FUOCO LEGGERO\nPESO: 5\nMUNIZIONI: 120\n\nEFFICACE CONTRO\t<Prigioniero dei sotteranei>\nRESISTENTE A\t<Guardiano del fiume>\n\nFucile mitragliatore celebre per la cadenza di fuoco e il grande calibro. Probabilmente appartenuta a qualche guardia dell'edificio\n";
const char* fucile_a_pompa_weapon_info="FUCILE A POMPA\nTIPO DI DANNO: DA FUOCO PESANTE\nPESO: 8\nMUNIZIONI: 8\n\nEFFICACE CONTRO\t<Esperimento squamato>\nRESISTENTE A\t<Soldato modificato>\n\nSpara una rosata di proiettili devastante sulle corte distanze. Danno alto ma pochi proiettili.\n";
const char* arpione_weapon_info="ARPIONE\nTIPO DI DANNO: SPECIALE\nPESO: 4\n\nEFFICACE CONTRO\t<Guardiano della Base>\nRESISTENTE A\t<Dottore pazzo>\n\nTipicamente utilizzato nella caccia subacquea, può risultare fatale anche nelle corte distanze in uno scontro sulla terra. Nel fiume non sembrano esserci specie viventi, che avesse un altro scopo?\n";
const char* lanciagranate_weapon_info="LANCIAGRANATE\nTIPO DI DANNO: ESPLOSIVO\nPESO: 7\nMUNIZIONI: 4\n\nEFFICACE CONTRO\t<Soldato modificato>\nRESISTENTE A\t<Combattente cyborg>\n\nSimile ad un fucile, con la differenza che i colpi esplodono all'impatto. Arma da guerra pesante, forse utilizzata per far collassare le pareti delle caverne. Danno alto, pochi colpi\n";
const char* balestra_esplosiva_weapon_info="BALESTRA ESPLOSIVA\nTIPO DI DANNO: ESPLOSIVO\nPESO: 6\nMUNIZIONI: 10\n\nEFFICACE CONTRO\t<Soldato modificato>\nRESISTENTE A\t<Combattente cyborg>\n\nRiprendendo il concept della tipica arma medievale, questa tipologia di balestra si differenzia dalla precedente per la presenza di dardi a lungo raggio altamente esplosivi all'impatto. ";
const char* sniper_weapon_info="SNIPER\nTIPO DI DANNO: DA FUOCO PESANTE\nPESO: 7\nMUNIZIONI: 12\n\nEFFICACE CONTRO\t<Esperimento squamato>\nRESISTENTE A\t<Soldato modificato>\n\nFucile in dotazione agli esploratori, incredibilmente potente sule lunghe distanze, grazie alla canna lunga e al calibro <308>\n";
const char* lanciafiamme_weapon_info="ROKS-2\nTIPO DI DANNO: SPECIALE\nPESO: 9\nRICARICHE DI COMBUSTIBILE: 3\n\nEFFICACE CONTRO\t<Guardiano della Base>\nRESISTENTE A\t<Dottore pazzo>\n\nQuesto lanciafiamme è stato creato sul fronte sovietico durante la Seconda Guerra mondiale. Cosa ci fa in una base americana? Che uso ne veniva fatto all'interno della base? L'efficacia maggiore si ottiene sulle corte distanze e su un gruppo di bersagli.";
const char* lanciarazzi_weapon_info="BAZOOKA\nTIPO DI DANNO: ESPLOSIVO\nPESO: 8\nRICARICHE DI RAZZI: 2\n\nEFFICACE CONTRO\t<Soldato modificato>\nRESISTENTE A\t<Combattente cyborg>\n\nNato come fucile anticarro, se non usato correttamente può essere devastante anche per l'utilizzatore data la grande forza esplosiva\n";
const char* pistola_particellare_weapon_info="PISTOLA PARTICELLARE\nTIPO DI DANNO: SPECIALE\n\nINFORMAZIONI:[CLASSIFICATE]\n";
const char* fucile_sperimentale_weapon_info="FUCILE SPERIMENTALE\nTIPO DI DANNO: SPECIALE\n\nINFORMAZIONE:[CLASSIFICATE]\n";

#endif
